(refs build-system) Fixed configure.ac and update build-scripts.

diff --git a/_2_build b/_2_build
--- a/_2_build
+++ b/_2_build
@@ -1,4 +1,16 @@
-#!/bin/sh
+#!/bin/bash
 
-./configure 1>log.txt 2>err.txt &&\
-make        1>log.txt 2>err.txt
+LOGFILE=log.txt
+ERRFILE=err.txt
+
+./configure 1>${LOGFILE} 2>${ERRFILE} && \
+make        1>${LOGFILE} 2>${ERRFILE}
+
+if [ "$?" = 0 ] ;
+then
+  echo "OK"
+else
+  tail ${ERRFILE} 
+  echo "ERROR while build"
+fi
+
